# Generated by Django 3.1.4 on 2020-12-22 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20201222_0322'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todos',
        ),
    ]
