# Generated by Django 3.1.4 on 2020-12-28 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_delete_todos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='text',
            field=models.TextField(max_length=5000),
        ),
    ]
